export const products = [
  {
    id: 1,
    name: "Café com leite",
    description: "O bom e velho café com leite",
    category: "Coffee",
    image: "/src/assets/products/coffee/1.svg",
    oldPrice: 2.99,
    isPromotion: true,
    price: 1.99,
    rating: 4.9,
  },
  {
    id: 2,
    name: "Café com leite de cacau e caramelo",
    description: "Leite vaporizado com mocha e cobertura de caramelo ",
    category: "Coffee",
    image: "/src/assets/products/coffee/2.svg",
    oldPrice: 14.99,
    isPromotion: true,
    price: 10.43,
    rating: 4.6,
  },
  {
    id: 3,
    name: "Nitro cold brew",
    description: "Café preparado com nitrogênio, sem açúcar e creme aveludado",
    category: "Coffee",
    image: "/src/assets/products/coffee/3.svg",
    oldPrice: 16.99,
    isPromotion: false,
    price: 12.89,
    rating: 4.4,
  },
  {
    id: 4,
    name: "Café Mocha",
    description: "Café expresso com cobertura mocha, leite e creme batido",
    category: "Coffee",
    image: "/src/assets/products/coffee/4.svg",
    oldPrice: 12.99,
    isPromotion: true,
    price: 11.6,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Caramel Latte",
    description: "Café expresso, leite fresco e caramelo",
    category: "Coffee",
    image: "/src/assets/products/coffee/5.svg",
    oldPrice: 9.99,
    isPromotion: false,
    price: 7.89,
    rating: 4.8,
  },
  {
    id: 6,
    name: "Coca-cola lata 350ml",
    description:
      "Com a tradição e o gosto incomparável, ela se torna a melhor opção de refresco em qualquer momento. ",
    category: "Drinks",
    image: "/src/assets/products/drinks/1.png",
    oldPrice: 4.99,
    isPromotion: false,
    price: 3.89,
    rating: 4.8,
  },
  {
    id: 7,
    name: "Pepsi lata 350ml",
    description:
      "A Pepsi Lata 350ml é um refrigerante de cola com aroma natural, apreciada pelo sabor suave e refrescante. ",
    category: "Drinks",
    image: "/src/assets/products/drinks/2.png",
    oldPrice: 4.89,
    isPromotion: false,
    price: 4.29,
    rating: 4.7,
  },
  {
    id: 9,
    name: "NESCAU prontinho 200ml",
    description: "Uma opção nutritiva e gostosa para seus filhos.",
    category: "Drinks",
    image: "/src/assets/products/drinks/4.png",
    oldPrice: 2.89,
    isPromotion: true,
    price: 1.96,
    rating: 4.4,
  },
  {
    id: 10,
    name: "Croissant",
    description: "O clássico pão francês.",
    category: "Pastry",
    image: "/src/assets/products/foods/1.png",
    oldPrice: 4.99,
    isPromotion: false,
    price: 4.29,
    rating: 4.7,
  },
];
